
logging:
  level:
    net.oneandone.reactive: DEBUG
    kafka: ERROR

schemaregistry: 
       schema.uri: classpath:schemas/schemas.zip

eventbus:
       bootstrapservers: localhost:8553
       zookeeper: localhost:8653
