
logging:
  level:
    net.oneandone.reactive: WARNING
    kafka: OFF
    org: OFF


schemaregistry: 
       path: src/main/resources/schemas

eventbus:
       bootstrapservers: localhost:8553
       zookeeper: localhost:8653
