
logging:
  level:
    net.oneandone.reactive: DEBUG
    kafka: ERROR


schemaregistry: 
       path: src/main/resources/schemas

eventbus:
       bootstrapservers: localhost:8553
       zookeeper: localhost:8653
